#define IS_DEBUG true

#define DEBUG_SHOWVALUES (true && IS_DEBUG) // SHOW SOME DEBUGGING VALUES?

#define DEBUG_STARTMATCH (false && IS_DEBUG) // START FROM THE BEGINNING OF THE MATCH?

#define DEBUG_SHOWACTIONDECISIONS (false && IS_DEBUG) // SHOW THE DECISIONS OF PLAYERS

#define DEBUG_SHOW_WITHBALLDECISIONS (false && IS_DEBUG) // SHOW THE DECISIONS OF PLAYERS WITH THE BALL